### PR TITLE
Improve graph color codes + legend. Add responsive behaviour for canvas.

### PR DESCRIPTION
**Pull request by idotj**
Rearrange values and color codes, improve readability with dotted lines and a lighter background color. Also the canvas graph now is responsive and will try to fill the space available on the screen (if the screen resolution changes, then the page reloads automatically to update the size)

### CODE REVIEW

**Comment by idotj** [comment]
Please let me know how looks in your devices, here I tested on my tablet and laptop and works fine under Firefox and Chrome (last version)

If the changes are ok the idea with this new color combinations is to add a dark theme (automatically detected by browser or device preference)
image

**Comment by nophead** [comment]
When the window size is changed it redraws but it seems to go back to the default 5 minute view.

I don't like the new colour scheme. I preferred lux to bright yellow like the sun and the particles to be grey like dust.

And the key is missing that shows the scale factors.

**Comment by nophead** [comment]
And it doesn't fit my phone screen.

**Comment by idotj** [comment]
Thanks for your feedback, I added the changes that you mentioned, please have a look.

What worries me it's your last message... if I remember you have a moto e5 play, so I emulated on my browser with the same resolution and after some tests, I updated the JS and CSS code to re-scale the graph on small resolutions.

**Comment by idotj** [comment]
I updated the code changing some responsive behavior for very small screens (the graph will pass under the table readings allowing a better arrangement in vertical display orientation)

**Comment by nophead** [comment]
What was wrong with the scale factors under the graph. They don't fit on my desktop screen down the side. And what was wrong with the original bold colours?

image


It used to fit fine on my phone and now it doesn't, so I don't understand what responsive means. 

Screenshot_20220226-193640

**Comment by idotj** [comment]
Thanks for uploading the screenshots!
Concerning your first question, the colors were changed to follow the WCAG standards. Colors with a low contrast ratio are hard to read for people with visibility problems. Also will not work in a future dark theme (black background).
About the scale factors at the left side, it's just to save room (height) for the graph.

The responsive in the past version was developed as a desktop version hacking the pixel size (that's why only fits using the desktop mode in the mobile browser)
Now has a real pixel size (the text will keep the same size for all screen and devices without need to zoom or enable desktop mode in a mobile browser) 

I hope that will answer your questions, feel free to share any suggestion to improve the design. Any ideas are welcome.
Thanks

**Comment by nophead** [comment]
I don't understand your point about the colours. The originals had maximum contrast in my view of the world as they were primary and secondary colours. The new ones have less contrast as they are more like pastel shades. I am normally sighted but find it hard to distinguish light and reducing, particularly because the lines are very thin now and they are browny / yellowy.

With the original version I can zoom the screen on my mobile or desktop to make it fit. With the "responsive"  version I can only make it bigger and not smaller, so it is always too big. I also have to expand the key and then scroll it. Before it was just there.

**Comment by idotj** [comment]
To analyze and get the ratio of contrast you need a foreground color and a background color, and then you can check with this tool if the combination will pass the WCAG contrast:
https://webaim.org/resources/contrastchecker/
If we take the original color for the light (yellow #FFFF00) and the background (gray #EEEEEE) you will see that the contrast ratio is 1.08:1, far from the recommended ratio for graphs (3:1)
Because I was working in a future black background, the ratio will also fail if the user has a dark theme (now very on demand for last Android versions) and to prevent that problem with a black background, I was testing different combinations to have a color that will work with white and black background.
I hope this will explain how to deal with the color contrast, but listen everybody has a different perception and with colors and design it's always hard to find the middle point.
If you prefer to keep your color combination because suits for you, I understand and in that case I will rather cancel this pull request.
Let me know if you would like to keep any other changes, to pull it in another PR.
Thanks

**Comment by nophead** [comment]
This PR seems to be aimed at two things. Better contrast for people that don't see colours normally and better fitting multiple screen sizes. The problem is for me, with normal vision, it is worse at both. I find the colours and line width less clear and I can't get it it to fit properly on my desktop or phone, whereas the current version I can just zoom until everything fits.

Perhaps the responsive version can be fixed to automatically zoom to fit the screen but I like the key where it was and not a drop down. The colour change would need to be an option because I don't think making it worse for the majority of the population to cope with for the minority with a whole range of colour perception problems is practical, especially when so many colours are used. With normal vision the main graph lines are as far apart as they can be and the dust is a grey scale representing size, so different from the others and themselves in another axis.

Before this change the background was CCCCCC, i.e. darker. I don't like bright backgrounds as they occasionally trigger migraines for me and it gives better contrast with brighter colours.

**Comment by idotj** [comment]
Hi there,
Sorry for my late answer (quite busy this week). I think that it will be better to cancel the PR just because the changes are not going to improve your use and in my case is the opposite (with the current version, the colors are too bright and the scale factor is something that I don't need it because I know already the max. and min.) So I think that my changes are too personal or adapted just to my needs.
Anyways I appreciate your feedback and time to answer, thanks to your work it was very easy to start to play with my enviro+
All the best,
i.j

**Comment by nophead** [comment]
OK, you could maintain a separate fork and put a link to it in the README here if you wan't as some people may prefer your version.

**Comment by idotj** [comment]
Sounds good to me,
I sent you a new PR with the link pointing to the forked version.
Thanks

**Pull request closed without merging**
