### PR TITLE
Add HTML5 structure + improve UX/UI

### PR DESCRIPTION
**Pull request by idotj**
Main index.html document has now a HTML5 structure.
W3C validator "passed"
Added a better responsive experience for small screen resolutions
Added Accessibility "a11y" standards
Rearrange layouts for a better user experience
Added icons for settings at the header
Added link to repo (github)

### CODE REVIEW

**Comment by idotj** [comment]
Thanks for your work, it allowed me to have a quick start with my enviro+
Now I can read all the data from my phone or tablet :)

**Comment by nophead** [comment]
Nice, thanks. Learnt HTML 20 years ago so no knowledge of HTML5.

**Comment by nophead** [comment]
Hmm, doesn't work on my phone. Seems to ignore the new style and has two massive icons. It is as if it hasn't reloaded the style sheet but I don't know how to force that on Android chrome. On my wife's phone that has never seen the page before it gets the new style but the footer floats over the data and graph, which are too big for the screen. With my original page it worked fine on my phone because I could shrink the graph to fit.

**Comment by idotj** [comment]
First try to load the page on your Chrome browser in Private mode (to be sure that the problem is not related with the browser)

If works, then you just need to clean the cache.
Open Chrome and head to Settings.
Then, click on Site Settings > All sites
Here, you'll see all the stored data for websites, including cache and cookies.
Select and clear the data for the website you want to.


About the footer, I send you a PR with the fix,
Thanks

**Comment by nophead** [comment]
Yes it gets the new style in private mode but I have already deleted all the site data and it still didn't work in normal mode. It didn't have an entry for this site but I cleared all sites anyway. I went into the app memory settings and deleted the Chrome cache from there and that gets the new style sheet. I hate mobile phones!

This is what it looks like on my phone now:
Screenshot_20210825-182746
 
I can expand the screen but I can't contract it.

I have a moto e5 play with a screen size of 720x1280 running Android 8.1.0. My wife's phone is a moto G9 power.

On my desktop the default graph size is too small but I can make it bigger with zoom.

image

If I tear off the tab and shrink the window then it also gets the banner over the graph. It doesn't seem to set the size of the graph correctly at all.

**Comment by idotj** [comment]
Thanks for the screenshots,
A new PR has the fix for the footer and for the header :)

In the future, will be nice if the graph fills the screen automatically (doesn't matter the size) I got some ideas in mind, hope to find some free time to play first...

**Pull request merged**
